@startuml Lass State Machine

skinparam layout neato
skinparam linetype ortho

state ModeLoiterAssisted {

' States
state "init()" as init: \
runs checks and initializes variables

state "ModeLoiterAssisted" as mode_lass: \
sets loiter assisted as current mode

state "Last Mode" as mode_last: \
Reject LASS mode and return to the previous flight mode

state c <<choice>>

' Transitions
[*] -[#black]-> init : set_mode()
init -[#black]-> c
c -[#black]-> mode_lass : if (AltHoldModeState::Flying || attached)
c -[#black]-> mode_last : else

' ==========================
--

state "run()" as run{

' States
state Lass: \
Pilot velocity control relative to dock. \n\
heading locked

State AttachManeuver {
State LeadUp: \
use velocity control to hit static vel vector to dock \n\
static heading pointed at dock 

State CoastIn: \
pitch set based on lead up \n\
roll, pitch, yaw rates to zero

State WindDown: \
gently reduce throttle. \n\
relax roll, pitch, \n\
command zero yaw rate
}

state Vegetable: \
disable crash checks \n\
mode changes still allowed \n\
considered a landed state

State DetachManeuver {
State WindUp: \
slowly wind up throttle until pitch target is hit \n\
relax pitch and roll \n\
try and hold zero yaw rate

State CoastOut: \
send detach signal to mcu \n\
target zero roll and 5 deg pitch \n\
hold zero yaw rate

State Recover: \
use pos control to get to recovery position
}

State Default: \
go to normal loiter code when nothing detected

' State Abort: \
' abort state to escape blade

' Transitions
[*] -[#black]-> Default
Default -[#red]-> Lass : DOCK_FOUND
Default -[#red]-> WindDown : ATTACHED
Lass -[#green]-> Default : !DOCK_FOUND
Lass -[#green]-> LeadUp : DOCKING_ENGAGED
Lass -[#green]-> WindDown : ATTACHED
LeadUp -[#black]-> CoastIn : WITHIN_COAST_IN_DIST
LeadUp -[#black]-> WindDown : ATTACHED
LeadUp -[#black]-> Lass : DETACH_BUTTON_PRESSED
CoastIn -[#red]-> WindDown : ATTACHED
' CoastIn -[#black]-> Abort : FALLING
WindDown -[#green]-> Vegetable : WINDED_DOWN
' WindDown -[#black]-> Abort : FALLING
Vegetable -[#black]-> WindUp : !ATTACH_BUTTON_PRESSED
WindUp -[#red]-> CoastOut : STABLE_AT_WIND_UP_PITCH
WindUp -[#red]-> WindDown : ATTACH_BUTTON_PRESSED
CoastOut -[#green]-> Recover : BEYOND_COAST_OUT_DIST
Recover -[#black]-> Lass : AT_RECOVERY_POSITION
}

State AbortExit: \
Leave lass state, try to return to \n\
last state, otherwise stabilize
 
[*] -[#black]-> run : update_flight_mode()
run -[#black]-> [*] : lass_disengage
run -[#black]-> AbortExit : No Pos Estimate
AbortExit -[#black]-> [*]
}



@enduml

' https://plantuml.com/state-diagram
